# Setup

In [2]:
import os
import numpy as np
import pandas as pd
from scipy import stats

AIRBNB_PATH = os.path.join("data", "airbnb")

def get_data_from_csv_file(file_name, aribnb_path=AIRBNB_PATH):
    path = os.path.join(aribnb_path, file_name)
    return pd.read_csv(path)

# Test T

### kmeans_cluster_based_on_numerical_and_categorical_variables_0

In [3]:
airbnb_0 = get_data_from_csv_file("kmeans_cluster_based_on_numerical_and_categorical_variables_0.csv")
airbnb_0.head()

,host_is_superhost,cancellation_policy,instant_bookable,host_total_listings_count,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,price,cluster
0,f,strict_14_with_grace_period,f,10,Haight Ashbury,37.76669,-12.24525,Apartment,Private room,2,...,17,85.0,8.0,8.0,9.0,9.0,9.0,8.0,65.0,0
1,t,strict_14_with_grace_period,f,2,Potrero Hill,37.75645,-12.23991,Apartment,Private room,2,...,272,98.0,10.0,10.0,10.0,10.0,10.0,9.0,155.0,1
2,f,strict_14_with_grace_period,t,2,Western Addition,37.77478,-12.24315,Apartment,Entire home/apt,10,...,31,90.0,9.0,8.0,9.0,9.0,9.0,9.0,450.0,0
3,t,moderate,f,9,Pacific Heights,37.79312,-1.22426,Apartment,Private room,1,...,160,92.0,10.0,9.0,10.0,10.0,10.0,9.0,55.0,1
4,t,moderate,f,9,Pacific Heights,37.79166,-12.24265,Apartment,Entire home/apt,2,...,38,93.0,9.0,9.0,10.0,10.0,10.0,9.0,115.0,1

In [9]:
airbnb_0["cluster"].value_counts()

1    664
0     39
Name: cluster, dtype: int64

In [4]:
airbnb_0.groupby("cluster").mean()

,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,price
cluster,,,,,,,,,,,,,,,,,
0,59.461538,35.154005,-11.960463,3.589744,1.820513,1.641026,2.589744,20.410256,13.871795,76.871795,8.000000,7.512821,8.743590,8.512821,8.538462,7.538462,149.230769
1,51.933735,34.216035,-10.979870,3.096386,1.204819,1.292169,1.674699,15.194277,43.219880,97.015060,9.917169,9.786145,9.960843,9.960843,9.796687,9.626506,197.686747

In [5]:
a = airbnb_0[airbnb_0["cluster"] == 0]["review_scores_rating"].values
b = airbnb_0[airbnb_0["cluster"] == 1]["review_scores_rating"].values

stats.ttest_ind(a, b)

Ttest_indResult(statistic=-28.120057854336878, pvalue=4.583223745536952e-117)

In [6]:
a = airbnb_0[airbnb_0["cluster"] == 0]["review_scores_cleanliness"].values
b = airbnb_0[airbnb_0["cluster"] == 1]["review_scores_cleanliness"].values

stats.ttest_ind(a, b)

Ttest_indResult(statistic=-21.624706648053248, pvalue=7.594994498546793e-80)

In [7]:
a = airbnb_0[airbnb_0["cluster"] == 0]["review_scores_value"].values
b = airbnb_0[airbnb_0["cluster"] == 1]["review_scores_value"].values

stats.ttest_ind(a, b)

Ttest_indResult(statistic=-20.30503676232248, pvalue=1.90949662631026e-72)

In [8]:
a = airbnb_0[airbnb_0["cluster"] == 0]["price"].values
b = airbnb_0[airbnb_0["cluster"] == 1]["price"].values

stats.ttest_ind(a, b)

Ttest_indResult(statistic=-1.879937295697811, pvalue=0.06053110663220381)

### kmeans_cluster_based_on_numerical_and_categorical_variables_1

In [10]:
airbnb_1 = get_data_from_csv_file("kmeans_cluster_based_on_numerical_and_categorical_variables_1.csv")
airbnb_1.head()

,host_is_superhost,cancellation_policy,instant_bookable,host_total_listings_count,neighbourhood_cleansed,latitude,longitude,property_type,room_type,accommodates,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,price,cluster
0,t,moderate,t,1,Western Addition,37.76931,-122.43386,Apartment,Entire home/apt,3,...,180,97.0,10.0,10.0,10.0,10.0,10.0,10.0,170.0,1
1,f,strict_14_with_grace_period,f,2,Bernal Heights,37.74511,-122.42102,Apartment,Entire home/apt,5,...,111,98.0,10.0,10.0,10.0,10.0,10.0,9.0,235.0,1
2,f,strict_14_with_grace_period,f,10,Haight Ashbury,37.76487,-122.45183,Apartment,Private room,2,...,8,93.0,9.0,9.0,10.0,10.0,9.0,9.0,65.0,1
3,f,strict_14_with_grace_period,f,2,Western Addition,37.77525,-122.43637,House,Entire home/apt,5,...,27,97.0,10.0,10.0,10.0,10.0,10.0,9.0,785.0,1
4,f,moderate,f,1,Western Addition,37.78471,-122.44555,Apartment,Entire home/apt,6,...,31,90.0,9.0,8.0,10.0,10.0,9.0,9.0,255.0,1

In [11]:
airbnb_1["cluster"].value_counts()

1    5981
0     462
Name: cluster, dtype: int64

In [12]:
airbnb_1.groupby("cluster").mean()

,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,beds,minimum_nights,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,price
cluster,,,,,,,,,,,,,,,,,
0,39.402597,33.330706,-122.428664,2.766234,1.400433,1.11039,1.642857,26.049784,26.558442,81.034632,8.519481,8.196970,9.015152,8.792208,8.759740,8.110390,150.324675
1,53.654573,34.388287,-122.430918,3.243772,1.271694,1.36432,1.778465,15.066711,45.097308,97.208995,9.921919,9.820264,9.964220,9.955359,9.792342,9.635178,220.327370

In [13]:
a = airbnb_1[airbnb_1["cluster"] == 0]["review_scores_rating"].values
b = airbnb_1[airbnb_1["cluster"] == 1]["review_scores_rating"].values

stats.ttest_ind(a, b)

Ttest_indResult(statistic=-71.35595967382679, pvalue=0.0)

In [15]:
a = airbnb_1[airbnb_1["cluster"] == 0]["review_scores_cleanliness"].values
b = airbnb_1[airbnb_1["cluster"] == 1]["review_scores_cleanliness"].values

stats.ttest_ind(a, b)

Ttest_indResult(statistic=-61.3673843373833, pvalue=0.0)

In [16]:
a = airbnb_1[airbnb_1["cluster"] == 0]["review_scores_value"].values
b = airbnb_1[airbnb_1["cluster"] == 1]["review_scores_value"].values

stats.ttest_ind(a, b)

Ttest_indResult(statistic=-49.64994920960325, pvalue=0.0)

In [14]:
a = airbnb_1[airbnb_1["cluster"] == 0]["price"].values
b = airbnb_1[airbnb_1["cluster"] == 1]["price"].values

stats.ttest_ind(a, b)

Ttest_indResult(statistic=-4.484393678280937, pvalue=7.4389746133489415e-06)